### ISSUE TITLE
request github.com/wikimedia/mediawiki-extensions-Purge to be created

### ISSUE THREAD

**Issue by adrelanos** [AlPha5130/mediawiki-extensions-Purge#1]
I don't know how that works but could you please request https://github.com/wikimedia/mediawiki-extensions-Purge to be created if feasible?

It has some advantages such as bot by wikimedia auto updating dependencies, submitting translations and auto branching for the various mediawiki releases.

**Comment by kizule** [comment]
wikimedia/mediawiki-extensions-* are created by WMF as mirror from Gerrit, when repository gets created on Gerrit.

**Comment by NekoCharm01** [comment]
Yes, those repos are mirrors from https://gerrit.wikimedia.org, and this repo does not need it. The only concerning thing is translation, which requires creating a ticket in Phabricator.

**Comment by kizule** [comment]
Actually, I guess we can switch updating translations from Hutchy68/Purge to your repo. What do you think? I can try to make it for you.

**Comment by NekoCharm01** [comment]
That will be very helpful! Thank you for the work.

**Comment by kghbln** [comment]
Created a pull to get this one into code search: https://github.com/MWStake/nonwmf-extensions/pull/53

**Comment by labster** [comment]
That was merged, so I think this issue can be closed.

**Comment by NekoCharm01** [comment]
Closed as it was included in code search.
